const isoToLanguageName = {
  af: "Africâner",
  am: "Amárica",
  ar: "Árabe",
  az: "Azerbaijana",
  be: "Bielorrussa",
  bg: "Búlgara",
  bn: "Bengalesa",
  ca: "Catalã",
  cs: "Tcheca",
  da: "Dinamarquesa",
  de: "Alemã",
  el: "Grega",
  en: "Inglesa",
  eo: "Esperantista",
  es: "Espanhola",
  et: "Estoniana",
  eu: "Basca",
  fa: "Persa",
  fi: "Finlandesa",
  fr: "Francesa",
  gl: "Galega",
  gu: "Guzerate",
  he: "Hebraica",
  hi: "Hindi",
  hr: "Croata",
  hu: "Húngara",
  hy: "Armênia",
  id: "Indonésia",
  is: "Islandesa",
  it: "Italiana",
  ja: "Japonesa",
  ka: "Georgiana",
  kk: "Cazaque",
  km: "Khmer",
  kn: "Canarim",
  ko: "Coreana",
  lt: "Lituana",
  lv: "Letã",
  mk: "Macedônia",
  ml: "Malaiala",
  mn: "Mongol",
  mr: "Marata",
  ms: "Malaia",
  mt: "Maltesa",
  nb: "Norueguesa Bokmål",
  nl: "Holandesa",
  nn: "Norueguesa Nynorsk",
  no: "Norueguesa",
  pl: "Polonesa",
  pt: "Portuguesa",
  ro: "Romena",
  ru: "Russa",
  sk: "Eslovaca",
  sl: "Eslovena",
  sq: "Albanesa",
  sr: "Sérvia",
  sv: "Sueca",
  sw: "Suaíli",
  ta: "Tâmil",
  te: "Télugo",
  th: "Tailandesa",
  tl: "Tagalo",
  tr: "Turca",
  uk: "Ucraniana",
  ur: "Urdu",
  vi: "Vietnamita",
  cn: "Cantonesa",
  zh: "Chinesa",
};


export const TranslateOriginalLanguage = ({ isoLanguage }) => {
  return isoToLanguageName[isoLanguage] || isoLanguage;
};
