const isoToCountryName = {
  AF: "Afegãs",
  AX: "Alandesas",
  AL: "Albanesas",
  DZ: "Argelinas",
  AS: "Samoanas Americanas",
  AD: "Andorranas",
  AO: "Angolanas",
  AI: "Anguilanas",
  AQ: "Antárticas",
  AG: "Antiguanas e Barbudanas",
  AR: "Argentinas",
  AM: "Armênias",
  AW: "Arubanas",
  AU: "Australianas",
  AT: "Austrianas",
  AZ: "Azerbaijanas",
  BS: "Bahamenses",
  BH: "Barenitas",
  BD: "Bangladeshianas",
  BB: "Barbadenses",
  BY: "Bielorrussas",
  BE: "Belgas",
  BZ: "Belizenhas",
  BJ: "Beninesas",
  BM: "Bermudenses",
  BT: "Butanesas",
  BO: "Bolivianas",
  BQ: "Caribenhas Neerlandesas",
  BA: "Bósnias e Herzegovinas",
  BW: "Botsuanas",
  BV: "Bouvetianas",
  BR: "Brasileiras",
  IO: "Britânicas do Oceano Índico",
  BN: "Bruneanas",
  BG: "Búlgaras",
  BF: "Burquinenses",
  BI: "Burundinesas",
  CV: "Cabo-Verdianas",
  KH: "Cambojanas",
  CM: "Camaronenses",
  CA: "Canadenses",
  KY: "Caimanesas",
  CF: "Centro-Africanas",
  TD: "Chadianas",
  CL: "Chilenas",
  CN: "Chinesas",
  CX: "Natalinas",
  CC: "Cocos",
  CO: "Colombianas",
  KM: "Comorianas",
  CG: "Congolesas",
  CD: "Congolesas (Democráticas)",
  CK: "Cookianas",
  CR: "Costarriquenhas",
  CI: "Marfinenses",
  HR: "Croatas",
  CU: "Cubanas",
  CW: "Curaçolenhas",
  CY: "Cipriotas",
  CZ: "Tchecas",
  DK: "Dinamarquesas",
  DJ: "Djiboutianas",
  DM: "Dominicanas (Domínica)",
  DO: "Dominicanas (República)",
  EC: "Equatorianas",
  EG: "Egípcias",
  SV: "Salvadorenhas",
  GQ: "Guinéu-Equatorianas",
  ER: "Eritreias",
  EE: "Estonianas",
  SZ: "Suazis",
  ET: "Etíopes",
  FK: "Falklandesas",
  FO: "Feroesas",
  FJ: "Fijianas",
  FI: "Finlandesas",
  FR: "Francesas",
  GF: "Guianenses Francesas",
  PF: "Polinésias Francesas",
  TF: "Territorianas Francesas do Sul",
  GA: "Gabonenses",
  GM: "Gambianas",
  GE: "Georgianas",
  DE: "Alemãs",
  GH: "Ganesas",
  GI: "Gibraltinas",
  GR: "Gregas",
  GL: "Groenlandesas",
  GD: "Granadinas",
  GP: "Guadalupenses",
  GU: "Guamianas",
  GT: "Guatemaltecas",
  GG: "Guernesianas",
  GN: "Guineenses",
  GW: "Guineenses-Bissau",
  GY: "Guianenses",
  HT: "Haitianas",
  HM: "Heard e McDonald",
  VA: "Vaticanas",
  HN: "Hondurenhas",
  HK: "Hongkonguesas",
  HU: "Húngaras",
  IS: "Islandesas",
  IN: "Indianas",
  ID: "Indonésias",
  IR: "Iranianas",
  IQ: "Iraquianas",
  IE: "Irlandesas",
  IM: "Manx",
  IL: "Israelenses",
  IT: "Italianas",
  JM: "Jamaicanas",
  JP: "Japonesas",
  JE: "Jersianas",
  JO: "Jordanas",
  KZ: "Cazaques",
  KE: "Quenianas",
  KI: "Kiribatianas",
  KP: "Norte-Coreanas",
  KR: "Sul-Coreanas",
  KW: "Kuwaitianas",
  KG: "Quirguizes",
  LA: "Laosianas",
  LV: "Letãs",
  LB: "Libanesas",
  LS: "Lesotianas",
  LR: "Liberianas",
  LY: "Líbias",
  LI: "Liechtensteinianas",
  LT: "Lituanas",
  LU: "Luxemburguesas",
  MO: "Macaenses",
  MG: "Malgaxes",
  MW: "Malauianas",
  MY: "Malaias",
  MV: "Maldivas",
  ML: "Malinesas",
  MT: "Maltesas",
  MH: "Marshallinas",
  MQ: "Martinicanas",
  MR: "Mauritanas",
  MU: "Mauricianas",
  YT: "Maiotenses",
  MX: "Mexicanas",
  FM: "Micronésias",
  MD: "Moldavas",
  MC: "Monegascas",
  MN: "Mongóis",
  ME: "Montenegrinas",
  MS: "Montserratianas",
  MA: "Marroquinas",
  MZ: "Moçambicanas",
  MM: "Mianmarenses",
  NA: "Namibianas",
  NR: "Nauruanas",
  NP: "Nepalesas",
  NL: "Neerlandesas",
  NC: "Neo-Caledônias",
  NZ: "Neozelandesas",
  NI: "Nicaraguenses",
  NE: "Nigerinas",
  NG: "Nigerianas",
  NU: "Niuianas",
  NF: "Norfolkianas",
  MP: "Marianas do Norte",
  NO: "Norueguesas",
  OM: "Omanenses",
  PK: "Paquistanesas",
  PW: "Palauanas",
  PA: "Panamenhas",
  PG: "Papuas-Nova Guiné",
  PY: "Paraguaias",
  PE: "Peruanas",
  PH: "Filipinas",
  PN: "Pitcairnesas",
  PL: "Polonesas",
  PT: "Portuguesas",
  PR: "Portorriquenhas",
  QA: "Cataris",
  RE: "Reunionesas",
  RO: "Romenas",
  RU: "Russas",
  RW: "Ruandesas",
  SA: "Sauditas",
  SN: "Senegalesas",
  RS: "Sérvias",
  SG: "Singapurianas",
  SK: "Eslovacas",
  SI: "Eslovenas",
  ZA: "Sul-Africanas",
  ES: "Espanholas",
  SE: "Suecas",
  CH: "Suíças",
  TH: "Tailandesas",
  TR: "Turcas",
  UA: "Ucranianas",
  AE: "Emiratenses",
  GB: "Britânicas",
  US: "Americanas",
  VE: "Venezuelanas",
  VN: "Vietnamitas",
};

const countryMap = {
  Afghanistan: "Afeganistão",
  Argentina: "Argentina",
  Australia: "Austrália",
  Austria: "Áustria",
  Belgium: "Bélgica",
  Brazil: "Brasil",
  Canada: "Canadá",
  "United Arab Emirates": "Emirados Árabes Unidos",
  Lebanon: "Líbano",
  China: "China",
  Denmark: "Dinamarca",
  Egypt: "Egito",
  Finland: "Finlândia",
  France: "França",
  Germany: "Alemanha",
  Greece: "Grécia",
  India: "Índia",
  Indonesia: "Indonésia",
  Iran: "Irã",
  Ireland: "Irlanda",
  Israel: "Israel",
  Italy: "Itália",
  Japan: "Japão",
  Mexico: "México",
  Netherlands: "Países Baixos",
  Norway: "Noruega",
  Pakistan: "Paquistão",
  Peru: "Peru",
  Philippines: "Filipinas",
  Poland: "Polônia",
  Portugal: "Portugal",
  Russia: "Rússia",
  "United States of America": "Estados Unidos",
  "United Kingdom": "Reino Unido",
  Spain: "Espanha",
  Sweden: "Suécia",
  Switzerland: "Suíça",
  Thailand: "Tailândia",
  Turkey: "Turquia",
  Ukraine: "Ucrânia",
  Vietnam: "Vietnã",
  "South Korea": "Coreia do Sul",
  "Czech Republic": "República Tcheca",
};

export const TranslateProductionCountry = ({ country, countryISO }) => {
  return (
    countryMap[country] || isoToCountryName[countryISO] || country || countryISO
  ); // Retorna a tradução, o nome original ou o código
};
